services:
  strands_agent:
    build:
      context: .
      dockerfile: Dockerfile.strands
    image: ${AGENT_CORE_CONTAINER_URI}
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AGENT_CORE_ARN: ${AGENT_CORE_ARN}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_USERNAME: ${COGNITO_USERNAME}
      COGNITO_PASSWORD: ${COGNITO_PASSWORD}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}

  langgraph_agent_as_mcp_tool:
    build:
      context: .
      dockerfile: Dockerfile.agent_as_tool
    image: ${AGENT_CORE_CONTAINER_URI}
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  langgraph_agent_a2a:
    build:
      context: .
      dockerfile: Dockerfile.a2a
    image: ${AGENTCORE_RUNTIME_CONTAINER_URI}
    ports:
      - "${AGENTCORE_RUNTIME_PORT:-9000}:${AGENTCORE_RUNTIME_PORT:-9000}"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_REGION: ${AWS_REGION}
      STAGE: ${STAGE:-dev}
      AGENTCORE_RUNTIME_URL: ${AGENTCORE_RUNTIME_URL}
      AGENTCORE_RUNTIME_PORT: ${AGENTCORE_RUNTIME_PORT:-9000}
