from dotenv import load_dotenv

load_dotenv()

import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
AWS_REGION = os.getenv("AWS_REGION")

AGENTCORE_RUNTIME_NAME = os.getenv("AGENTCORE_RUNTIME_NAME")
AGENTCORE_RUNTIME_CONTAINER_URI = os.getenv("AGENTCORE_RUNTIME_CONTAINER_URI")
AGENTCORE_RUNTIME_ROLE_ARN = os.getenv("AGENTCORE_RUNTIME_ROLE_ARN")
AGENTCORE_RUNTIME_SERVER_PROTOCOL = os.getenv("AGENTCORE_RUNTIME_SERVER_PROTOCOL")
AGENTCORE_RUNTIME_URL = os.getenv("AGENTCORE_RUNTIME_URL")
AGENTCORE_RUNTIME_ARN = os.getenv("AGENTCORE_RUNTIME_ARN")
AGENTCORE_RUNTIME_PORT = os.getenv("AGENTCORE_RUNTIME_PORT")

COGNITO_DISCOVERY_URL = os.getenv("COGNITO_DISCOVERY_URL")
COGNITO_CLIENT_ID = os.getenv("COGNITO_CLIENT_ID")
COGNITO_USER_POOL_ID = os.getenv("COGNITO_USER_POOL_ID")
COGNITO_USERNAME = os.getenv("COGNITO_USERNAME")
COGNITO_PASSWORD = os.getenv("COGNITO_PASSWORD")

MCP_URL = os.getenv("MCP_URL")
BEARER_TOKEN = os.getenv("BEARER_TOKEN")
STAGE = os.getenv("STAGE")

required_envs = []

for env in required_envs:
    if None in env.values():
        raise ValueError(f"Missing environment variable: {env.keys()}")
